package forward;

import java.util.Set;
import java.util.List;
import com.ftn.sbnz.model.models.dtos.RecommendedSongDTO;
import com.ftn.sbnz.model.models.UserPreference;
import com.ftn.sbnz.model.models.dtos.SongDTO;
import com.ftn.sbnz.model.models.Song;
import com.ftn.sbnz.model.models.User;
import com.ftn.sbnz.model.Message
import com.ftn.sbnz.model.models.Genre
import java.util.ArrayList
import java.util.HashSet
import java.util.stream.Collectors;

global Set<SongDTO> recommendations;

rule "When added song to favorites recommend a song by same genre"
when
    $song: Song()
then
    Genre genre = $song.getGenre();
    SongDTO newSong = SongDTO.builder()
    .name("New Song")
    .artist("Artist")
    .album("Album")
    .genre(genre.getGenre())
    .listensCount(100)
    .favoritesCount(7)
    .build();
    recommendations.add(newSong);
    insert(recommendations);
end
